### PR TITLE
Allow manually specifying channel for bluetooth rfcomm link

### PR DESCRIPTION
**Pull request by pilatomic**
Some devices expect a bluetooth connection on a specific RFCOMM channel. 
Currently the rfcomm channel is always set to 1. 
At least for one of my devices, this channel has to be set manually to 2, or the connection fails. 
Add option to specify RFCOMM channel as another CONN argument.

### CODE REVIEW

**Comment by pilatomic** [comment]
Fixed some style issues

**Comment by knarfS** [comment]
Over on IRC, @gsigh proposed the following implementation:

> don't like the implementation of PR 209 but can understand the motivation
> got something more generic here in my queue, BLE attribute handles kept bothering me for a long time
> https://repo.or.cz/libsigrok/gsi.git/shortlog/refs/heads/wip/conn-bt-params if anybody feels like testing, could also help generic BLE bridges

Would be great, if you could give this implementation a try and test it, if it works for you

**Comment by pilatomic** [comment]
Just tested the patchset from @gsigh, and I am able to connect to my device with the following command line : 
`sigrok-cli --driver atorch:conn=bt/rfcomm/48-A2-D2-AA-21-42/channel=2`
I can confirm this does indeed work perfectly fine for my use case

**Comment by pilatomic** [comment]
Fixed upstream

**Pull request closed without merging**
