### PR TITLE
Initial support of Hyelec-MS8236

### PR DESCRIPTION
**Pull request by mrgsts**
Initial support of Hyelec-MS8236, Aka BSIDE ADM20, BOLYFA 117, code based on MASTECH MS8250D

### CODE REVIEW

**Comment by abraxa** [comment]
Hello mrgsts, your PR has been around for a while and that's unfortunate. However, it hasn't been forgotten. As soon as someone with DMM knowledge on our core team is able to review the driver code, you'll either receive feedback or the driver will be merged. My apologies for the delay.

**Comment by gsigh** [comment]
oh, all the comments on the code in your repo have gone here, too? :-O
if you are looking for more lively feedback, consider joining the project's IRC channel, that's where most development discussion takes place
I could address most of the style issues since they are straight forward, but could not test due to lack of access to such a device

**Comment by gsigh** [comment]
Any comments on the feedback?

**Comment by mrgsts** [comment]
> Any comments on the feedback?

mi project ended, and i don't have access to the hardware anymore, so the merge can be cancelled, forgotten and buried

**Comment by gsigh** [comment]
Closing since there is uncertainty about the meter's communication protocol and currently no way to overcome that. The source code and the documentation disagree while there is no means to verify or fix either of them properly, it'd all be guessing. The implementation can continue and pick up where this current state left, after the required paperwork is done when somebody has access to the device.

**Pull request closed without merging**
