### PR TITLE
Adding support for Cypress FX3 device to libsigrok

### PR DESCRIPTION
**Pull request by ashwinnaircy**
EZ-USB FX3 is a USB 3.0 peripheral controller that comes from the EZ-USB family of products (USB 3.0 version of the FX2 series used in fx2lafw). Addition of FX3 support to sigrok can help developers to use any FX3 kit as a USB 3.0 logic analyzer.

### CODE REVIEW

**Comment by jevinskie** [comment]
Where is the source of the firmware? This is neat!

**Comment by ashwinnaircy** [comment]
Thanks for your comment. 

The firmware will actually fall under "Getting non-distributable firmware files" section of the firmware wiki (https://sigrok.org/wiki/Firmware). We are planning to release the binary (cypress-fx3.fw) and the firmware example project source through the Cypress webpage as a Knowledge Base Article. We cannot add the source or the binary to the sigrok-firmware project due to licensing issues.

**Comment by ashwinnaircy** [comment]
The firmware source is online at [EZ-USB™ FX3 Explorer kit as 16-channel 100 MHz logic analyzer with sigrok PulseView - KBA233652](https://community.cypress.com/t5/Knowledge-Base-Articles/EZ-USB-FX3-Explorer-kit-as-16-channel-100-MHz-logic-analyzer/ta-p/283993).

**Comment by abraxa** [comment]
For transparency purposes, here's the email I sent the author of this PR:

> Thanks for contributing, it is much appreciated!
> 
> Before I dive into this more deeply, I'd like to discuss the state of the firmware, as this is a critical piece of the system.
> 
> From my understanding, the sigrok project can neither distribute your firmware binary nor the complete source code to the firmware as it contains an OS that requires developers to agree to a license agreement before downloading the FX3 SDK. Is my understanding correct?
> 
> A sigrok user developed an alternative firmware that is completely open source which doesn't have these issues. As of now, however, the driver has issues with USB 2 -> 3 enumeration and acquisition is unstable at higher data rates. From our perspective, it is preferable to be able to have both the driver and the firmware under an open source license, so ideally we'd like to see this fully open firmware being polished and made usable.
> 
> While adding your driver certainly would be a step forward to users, it is somewhat unfortunate that the closed-source nature of the SDK counteracts the OSS benefits that sigrok aims to provide.
> 
> Hence, what I also would like to know is whether we could either interest you in helping out with our OSS FX3 driver/firmware or whether there is any possibility to get your FX3 firmware into a redistributable and/or user-buildable state without having to agree to additional license terms.

For these reasons, as much as I am happy to see Infineon step up and contribute, #154 is currently the preferred way forward. I'd be happy if we could somehow merge these efforts and get something that works better than each individual solution.

**Comment by linuxguy123** [comment]
Would this suffice as permission from Cypress ? (Infineon)

https://community.infineon.com/t5/USB-superspeed-peripherals/How-to-flash-from-command-line-CYUSB3KIT-003/m-p/244878#M24662

**Comment by kosma** [comment]
Is there any chance we can get a prebuilt installer in the KB article? The compilation process, while doable, is quite time-consuming.

**Comment by endjuser** [comment]
I see Infineon responded on their forum (per the post above, asking permission to use their firmware blob) but no one has followed up with them.  It sounds like they may be amenable to Sigrok distributing their blob.

It would be great to be able to use Sigrok with the FX3 firmware provided by the device manufacturer for this specific application, without having to set up a Sigrok build environment.

**Comment by LeisureLadi** [comment]
Since merging the here described Cypress-FX3 driver into sigrok is not likely to happen I grabbed the bull by the horns and set up a fresh Ubuntu-20.04 system on windows wsl2 to build sigrok-cli and pulseview from scratch. It took me about 2 weeks to get everything up and running, but now it is done and I thought it may be good to share the work to enable others to build this nice little piece of software themselves.

You can download the wsl image of Ubuntu-20.04 with all required libraries included, except for the 'cypress-fx3.fw' firmware due to the fact that it is covered by a different licensing scheme. You need to download it separately from infineon's web-site (link was provided by infineon earlier here).

You can copy the firmware to '~/sigrok-src/sigrok-firmware-fx3/', from where it will then be included in the windows installer. But you can add it later to the installed software as well like it is described in infineon's blog.

These are the links to the image:

[Image Part 0](https://mega.nz/file/cqsGRBSa#ZPnVXdlmgHQw-sfZgFUHtEFtTsKAefxx9IzBu1-pJBk)
[Image Part 1](https://mega.nz/file/gvVVDb4R#nUtgLKP7GYNC3Yx3dyac6i2pY2oJhSUNrOOkB8rf-yE)
[Image Part 2](https://mega.nz/file/JmUzERjA#UjIm3TqMK7FO2thjy0qt6tNBFVuYhR8-whEIkj5ue1I)

Total size of the image is about 11 GB, so I had to split the ".tar" file into 3 parts, since the daily download limit at the hoster is 5 GB on a free plan.

1) Download and merge all 3 files into a single one by using the linux' "cat" command.

2) Import the image into wsl and start it. The user password is "CypressFX3".

I'm using a static source for compiling sigrok, since I needed to manually integrate the FX3 driver modifications into 'libsigrok'. The build scripts located in '~/sigrok-utils/cross-compile/...' directories are modified to copy the source files from '~/sigrok-src' rather than "wget" them from git. If you want to use the latest git version, you should either "wget" them into '~/sigrok-src' or change the build scripts again, i.e. uncomment the "wget" commands and comment the following "mkdir" and "cp" commands.

If you use the git versions, you will, however, lose the modifications required for integration of the FX3 driver!

If you are up for cross compiling for mingw, you may want to download the FX3 firmware provided by infineon before compiling. Extract the 'cypress-fx3.fw' file and copy it to '~/sigrok-src/sigrok-firmware-fx3' directory. It will then be included in your personal windows installer.

3) Before compiling sigrok, you should check the available memory. You will need at least 4 GB available for linux. I had to increase virtual memory, which you can do as well by running "sudo bash make_vm". That increases VM by another 8GB.

4) Finally you can start compiling by changing to the corresponding subdirectory, where the build scripts are located (typ. '~/sigrok-util/cross-compile/linux' or '~/sigrok-util/cross-compile/mingw').

If you cross-compile for windows, please adjust the build script to compile for either 32 or 64 bits. The image's default is 64 bits.

Good luck and have fun!

**Comment by mrv96** [comment]
@LeisureLadi thank you for your work! I've just taken a look to it.

The directories in your image are not git clone, hence is not easy understand what you have done. I think that it would be great if you create a repository with modified scripts and provide a Dockerfile instead of the WSL image.

**Comment by nick-kraus** [comment]
Is the current concern blocking this PR from being merged the issue of permission from Infineon to redistribute the FX3 firmware found in the KBA by the sigrok project?

If so, I'm happy to attempt chasing an answer from Infineon on this, I just want to make sure that all is needed is for explicit permission of the sigrok project to redistribute the firmware files found on the KBA, and what form that permission can come in (whether a post on the Infineon forum, or something else).

I would love to see this get merged since the process of building from source for a windows installer seems rather arduous, and it will open up a great option for a cheap performant logic analyzer platform.

**Comment by abraxa** [comment]
> Is the current concern blocking this PR from being merged the issue of permission from Infineon to redistribute the FX3 firmware found in the KBA by the sigrok project?

I quote Cypress:

"We cannot add the source or the binary to the sigrok-firmware project due to licensing issues."

This is as big of a showstopper as it gets. Closing the PR as we're not interested in drivers whose firmware we can't redistribute.

I suggest further developments happens as part of #154.

**Comment by shabaz123** [comment]
Hello @LeisureLadi 
Many thanks for the WSL image. 
I had a question, are you able to capture at 100 MHz for any reasonable number of samples (e.g. 100M samples)?
I've built the MinGW version using the WSL image, and it seems the sample drop-down at the top gets ignored, or is incorrectly used. For instance, if the sample rate is 100 MHz, and the number of samples is set to 100 M samples, if I click run, it only captures for 5 usec (see screenshot below). Really bizarre.
Unfortunately I'm not familiar enough with the Pulseview source code to know where to even look to see what the issue could be.
pulseview-issue

**Comment by LeisureLadi** [comment]
Hi @shabaz123,

I'm too not familiar with the internal details of sigrok, but from recent bug reports I understand, that pulseview currently is broken on Windows due to an issue with libusb (see here: https://github.com/sigrokproject/libsigrok/pull/235).

I guess, there is no simple solution for the problem in the near future.

**Comment by LeisureLadi** [comment]
Hi @shabaz123,

a small, but important correction: with the modifications described here: [#242](https://github.com/sigrokproject/libsigrok/pull/242/files) it is possible to record with fx3 at 100MHz and long sampling times.

Thanks to  @multiplemonomials to provide the fix.

I'm not sure, if the timing is always correct, but at least recording is possible.

**Comment by yokrysty** [comment]
Hey guys
here is my take on build this
https://github.com/yokrysty/docker-pulseview-cc-mingw

**Comment by minecraft2048** [comment]
I don't think this is the right place to put this, but if the blocker of upstreaming FX3 is non-free ThreadX RTOS that makes Cypress not allowing us to redistribute firmware, then ThreadX is open source now: https://github.com/eclipse-threadx/threadx

**Comment by alexpopa87** [comment]
> For transparency purposes, here's the email I sent the author of this PR:
> 
> > Thanks for contributing, it is much appreciated!
> > Before I dive into this more deeply, I'd like to discuss the state of the firmware, as this is a critical piece of the system.
> > From my understanding, the sigrok project can neither distribute your firmware binary nor the complete source code to the firmware as it contains an OS that requires developers to agree to a license agreement before downloading the FX3 SDK. Is my understanding correct?
> > A sigrok user developed an alternative firmware that is completely open source which doesn't have these issues. As of now, however, the driver has issues with USB 2 -> 3 enumeration and acquisition is unstable at higher data rates. From our perspective, it is preferable to be able to have both the driver and the firmware under an open source license, so ideally we'd like to see this fully open firmware being polished and made usable.
> > While adding your driver certainly would be a step forward to users, it is somewhat unfortunate that the closed-source nature of the SDK counteracts the OSS benefits that sigrok aims to provide.
> > Hence, what I also would like to know is whether we could either interest you in helping out with our OSS FX3 driver/firmware or whether there is any possibility to get your FX3 firmware into a redistributable and/or user-buildable state without having to agree to additional license terms.
> 
> For these reasons, as much as I am happy to see Infineon step up and contribute, #154 is currently the preferred way forward. I'd be happy if we could somehow merge these efforts and get something that works better than each individual solution.

So if somebody rewrites the firmware without using the OS can this pull request be done?
Or shall the FX3 SDK be also removed from the firmware?
Considering that the firmware only contains only one thread, my guess is that it can easily be removed.

**Comment by praveen1709-hub** [comment]
> EZ-USB FX3 is a USB 3.0 peripheral controller that comes from the EZ-USB family of products (USB 3.0 version of the FX2 series used in fx2lafw). Addition of FX3 support to sigrok can help developers to use any FX3 kit as a USB 3.0 logic analyzer.



Hi, i am trying to build the pulseview from the source in rpi 4 i built the pulseview it is working but in that  libsigrok git i got from internet doen't have cypress-fx3 then i found out ur git have that code which i needed so i just removed that libsigrok and cloned urs and dit this cmd for the make process:

make clean
1. ./autogen.sh
2. ./configure
3. make
4. sudo make install
5. sudo ldconfig

and again re-built the pulseview still im not seeing the cypress-fx3 in the about of the pulseview, can anyone give some solutions for this?
it will be very useful

@ashwinnaircy

**Comment by alexpopa87** [comment]
> > These were the steps I had followed to generate Pulseview with cypress-fx3 support. The only reliably working option at that time to build for Windows was to cross-compile on Linux environment using MXE mingw binaries. I am not sure if this is still the case.
> > 
> > 1. Install dependencies from link ([Building - sigrok)](https://sigrok.org/wiki/Building).
> > 2. Windows WSL 1 environment is used instead of a Linux PC to cross-compile for Windows
> > 3. Instructions to cross-compile using MXE are available in building from source section ([Windows - sigrok](https://sigrok.org/wiki/Windows))
> > 4. Cross-compile using MXE
> >    a. Go to https://mxe.cc/ and follow instructions in Tutorial section to build mxe binaries required for sigrok
> >    b. Details are present in sigrok-util.git / cross-compile / mingw / README.
> >    c. Once the needed binaries are build, proceed to next step
> >    d. Run sigrok-cross-mingw script in sigrok-util repo to build all sigrok projects. Pulseview and sigrok-cli installers
> >    will be created in the respective folders.
> > 
> > Hope this helps.
> 
> thank you for this clarification but i'm doing the build in ubuntu so can u please tell that part like i created a virtual env and cloned the git's of libsigrok, libsigrokdecode and pulseview, and installed all the req packages
> 
> so now instead of that libsigrok from main repo i found this repo so tell me the process how to build this libsigrok and the pulseview like which cmd's i need to use.
> 
> @alexpopa87

https://youtu.be/ZttRQppxUME?si=QP2RXYMgeu8nJWrS

**Comment by praveen1709-hub** [comment]
> > > These were the steps I had followed to generate Pulseview with cypress-fx3 support. The only reliably working option at that time to build for Windows was to cross-compile on Linux environment using MXE mingw binaries. I am not sure if this is still the case.
> > > 
> > > 1. Install dependencies from link ([Building - sigrok)](https://sigrok.org/wiki/Building).
> > > 2. Windows WSL 1 environment is used instead of a Linux PC to cross-compile for Windows
> > > 3. Instructions to cross-compile using MXE are available in building from source section ([Windows - sigrok](https://sigrok.org/wiki/Windows))
> > > 4. Cross-compile using MXE
> > >    a. Go to https://mxe.cc/ and follow instructions in Tutorial section to build mxe binaries required for sigrok
> > >    b. Details are present in sigrok-util.git / cross-compile / mingw / README.
> > >    c. Once the needed binaries are build, proceed to next step
> > >    d. Run sigrok-cross-mingw script in sigrok-util repo to build all sigrok projects. Pulseview and sigrok-cli installers
> > >    will be created in the respective folders.
> > > 
> > > Hope this helps.
> > 
> > 
> > thank you for this clarification but i'm doing the build in ubuntu so can u please tell that part like i created a virtual env and cloned the git's of libsigrok, libsigrokdecode and pulseview, and installed all the req packages
> > so now instead of that libsigrok from main repo i found this repo so tell me the process how to build this libsigrok and the pulseview like which cmd's i need to use.
> > @alexpopa87
> 
> https://youtu.be/ZttRQppxUME?si=QP2RXYMgeu8nJWrS

thank u so much for this link i will look into it.

**Comment by ashwinnaircy** [comment]
Hi Praveen,  


The build script you're using to build Sigrok and its utilities will, by default, perform a git clone from the default Sigrok repository during the build process. You can observe this behavior in the sigrok-cross-mingw script, for example.  


This might explain why your build isn't reflecting the changes you've made in your local Sigrok repository. To resolve this, you need to point the build script to the Git paths of your git repository so that it clones and builds from there.  


A good approach would be to add log messages to the build process. This can help you verify what is being fetched and built to ensure the changes from your repository are included.

**Comment by ashwinnaircy** [comment]
> so my doubt is before cross-compiling the windows thing will it have the cypress-fx3 driver in the pulseview windows version? 

No, it will not have support for cypress-fx3 by default till you point the build script to build from the modified libsigrok sources in this PR. 

>when i use sigrok-cross-mingw, and mainly will i be able to edit the source code of pulseview thing like the clr and UI thing coz i think i will only get the .exe file by cross compiling which i can't manually edit after the build of pulseview @ashwinnaircy

Sorry, I am not sure I understand this correctly.  

From my understanding you have a linux native build that has cypress-fx3 already. Please confirm. 
And, you are trying cross compile for Windows now? If so, you need to specify which libsigrok you need to be included in the cross compile build script also (same as what you had to do for linux).

**Comment by praveen1709-hub** [comment]
> > so my doubt is before cross-compiling the windows thing will it have the cypress-fx3 driver in the pulseview windows version?
> 
> No, it will not have support for cypress-fx3 by default till you point the build script to build from the modified libsigrok sources in this PR.
> 
> > when i use sigrok-cross-mingw, and mainly will i be able to edit the source code of pulseview thing like the clr and UI thing coz i think i will only get the .exe file by cross compiling which i can't manually edit after the build of pulseview @ashwinnaircy
> 
> Sorry, I am not sure I understand this correctly.
> 
> From my understanding you have a linux native build that has cypress-fx3 already. Please confirm. And, you are trying cross compile for Windows now? If so, you need to specify which libsigrok you need to be included in the cross compile build script also (same as what you had to do for linux).

1. Yes i have a linux system with manually compiled pulseview with cypress-fx3 init.
2. Yes now  im trying to cross compile for windows, that linux part is over there im getting the fx3 driver working,so now i need to know how to manually make the build script to point the modified PR in which cmd i need to change in windows sigrok-cross-mingw?

i also got the reference view from @alexpopa87  https://youtu.be/ZttRQppxUME?si=QP2RXYMgeu8nJWrS
which u can see at the before comments, that is very detailed but i cant figure it out which cmd is for specifying the modified libsigrok repo @ashwinnaircy

**Comment by ashwinnaircy** [comment]
>Yes, now im trying to cross compile for windows, that linux part is over there im getting the fx3 driver working,so now i need to know how to manually make the build script to point the modified PR in which cmd i need to change in windows sigrok-cross-mingw?

You need to modify the [sigrok-cross-mingw](https://github.com/sigrokproject/sigrok-util/blob/master/cross-compile/mingw/sigrok-cross-mingw) file to specify the path to the libsigrok repo with the modified code. 
It should be `$GIT_CLONE $USER_REPO/libsigrok` instead of `$GIT_CLONE $REPO_BASE/libsigrok`

where `$USER_REPO ="https://github.com/ashwinnaircy/" ` or origin of your repo with the modified source. 

Hope this is what you are looking for.

**Comment by praveen1709-hub** [comment]
> > Yes, now im trying to cross compile for windows, that linux part is over there im getting the fx3 driver working,so now i need to know how to manually make the build script to point the modified PR in which cmd i need to change in windows sigrok-cross-mingw?
> 
> You need to modify the [sigrok-cross-mingw](https://github.com/sigrokproject/sigrok-util/blob/master/cross-compile/mingw/sigrok-cross-mingw) file to specify the path to the libsigrok repo with the modified code. It should be `$GIT_CLONE $USER_REPO/libsigrok` instead of `$GIT_CLONE $REPO_BASE/libsigrok`
> 
> where `USER_REPO ="https://github.com/ashwinnaircy/" ` or origin of your repo with the modified source.
> 
> Hope this is what you are looking for.

Yes this is what im looking for thankyou. But the thing is if i cross-compile this i will only get the executable file right not the (pulseview dir with codes and make files and UI files)??

**Comment by ashwinnaircy** [comment]
The [sigrok-cross-mingw](https://github.com/sigrokproject/sigrok-util/blob/master/cross-compile/mingw/sigrok-cross-mingw) script will fetch and build all the sigrok projects (which includes pulseview, libsigrok etc) and generate the corresponding .exe's or libraries in each project's folder. If you plan/want to modify Pulseview also, you should change the corresponding source files in your pulseview repo and point to the repo with the changed files during cross-compile (same as how you included the custom libsigrok). 

Pulseview will generate other directories like share/sigrok-firmware etc on installation of the .exe.

**Comment by praveen1709-hub** [comment]
> The [sigrok-cross-mingw](https://github.com/sigrokproject/sigrok-util/blob/master/cross-compile/mingw/sigrok-cross-mingw) script will fetch and build all the sigrok projects (which includes pulseview, libsigrok etc) and generate the corresponding .exe's or libraries in each project's folder. If you plan/want to modify Pulseview also, you should change the corresponding source files in your pulseview repo and point to the repo with the changed files during cross-compile (same as how you included the custom libsigrok).
> 
> Pulseview will generate other directories like share/sigrok-firmware etc on installation of the .exe.

Ok, thank you for the detailed clarification.

**Comment by alexpopa87** [comment]
@ashwinnaircy do you know if the RAW_IO patch for libusb1 is needed for cypress-fx3?
Or can the cypress be used with the generic libusb1?

**Comment by praveen1709-hub** [comment]
> > Yes, now im trying to cross compile for windows, that linux part is over there im getting the fx3 driver working,so now i need to know how to manually make the build script to point the modified PR in which cmd i need to change in windows sigrok-cross-mingw?
> 
> You need to modify the [sigrok-cross-mingw](https://github.com/sigrokproject/sigrok-util/blob/master/cross-compile/mingw/sigrok-cross-mingw) file to specify the path to the libsigrok repo with the modified code. It should be `$GIT_CLONE $USER_REPO/libsigrok` instead of `$GIT_CLONE $REPO_BASE/libsigrok`
> 
> where `USER_REPO ="https://github.com/ashwinnaircy/" ` or origin of your repo with the modified source.
> 
> Hope this is what you are looking for.

Hi @ashwinnaircy, the solution u suggested is not working.
     The issue im facing is with the libsigrok repo which having fx3 support, the details of the issue is im trying to add the git link like u said and i started the mingw way of cross compilation by selcting x86_64 in the sigrok-cross-mingw file in "sigrok-util/cross-compile/mingw" but when the libsigrok repo is configuring im facing this "Windows builds require the event-abstraction branch of libusb" so i tried the libsigrok repo which doesn't have fx3 support there im not geeting the issue 
     
     I followed the mingw cross compile steps as per instructed still same issue, cross verified still no ans for that
     
     the issue is in configure file of libsigrok(fx3 support repo) i cant modify the configure file also coz it wont take the files from my system anyway it will clone it new. So the only possible way now im having is cloning the repo and change the part "but still i dont know what to change also" and create a new  local repo and use that link. other than this do u have any solution i will add the configure file part which is showing the error.
     
     
     
LIBS=$sr_save_libs
CFLAGS=$sr_save_cflags

if test -z "$NEED_USB_TRUE"; then :
  case $sr_have_libusb_os_handle:$host_os in #(
  no:mingw*) :
    as_fn_error $? "Windows builds require the event-abstraction branch of libusb" "$LINENO" 5 ;; #(
  *) :
     ;;
esac

**Pull request closed without merging**
