### PR TITLE
input: add import module for Tektronix ISF file format

### PR DESCRIPTION
**Pull request by filipkosecek**
Tektronix devices use ISF format to store captured data. The format varies depending on the device, so the module tries to be as general as possible.

### CODE REVIEW

**Comment by marcows** [comment]
Why exactly did you close your PR #186, which already received some amount of review, and now open a new PR with the same topic?

**Comment by marcows** [comment]
Are you sure that was necessary because of the new fork?

**Comment by filipkosecek** [comment]
Unfortunately, I can't reopen the closed pull request, and it doesn't sync with the new fork. Therefore, I believe that opening a new pull request was the only option.

**Comment by filipkosecek** [comment]
@marcows Please let me know if this PR has any chance of being merged so that I know whether I should keep working on it or quit. Thanks in advance.

**Comment by marcows** [comment]
@filipkosecek, beside from reviewing I don't have an influence on this process.
As far as I got to know this project, reviewing is one of the most important things for submissions having the chance being applied to upstream.

However, I got a new job this year and don't need an oscilloscope anymore, so unfortunately I don't have a personal interest in the .ist import module anymore (I only needed the oscilloscope once to identify a communication problem for a few days or weeks anyway).

**Review by biot — COMMENTED** [review]
@filipkosecek Any chance of getting some ISF files for the sigrok-dumps repo? Would be really nice to be able to test against some real-world files, ideally enough to test the different BN_FMT and BYT_NR options.

**Review by biot — APPROVED** [review]

**Review by biot — APPROVED** [review]

**Comment by filipkosecek** [comment]
@biot I have a couple of files which could be used. However, I thought the sigrok-dumps repo was intended only for .sr files which correspond to various protocols, or should I just upload the ISF files to it?

**Comment by abraxa** [comment]
Hello @filipkosecek, I'd appreciate if you could add them to the sigrok-dumps repo. There are already .ad files for the Trace32 input module in the trace32_demo directory of https://sigrok.org/gitweb/?p=sigrok-dumps.git;a=tree;f=misc , for example. It makes sense to add a tektronix_isf directory and add your files there.

**Comment by filipkosecek** [comment]
@abraxa Hi, I am currently on a vacation, but will add them to the repo when I'm back home next week.

**Comment by filipkosecek** [comment]
@biot @abraxa I've uploaded examples to sigrok-dumps https://github.com/sigrokproject/sigrok-dumps/pull/47.

**Review by abraxa — APPROVED** [review]

**Comment by abraxa** [comment]
Merged as https://sigrok.org/gitaction/libsigrok.git/0dfa850..b890d23, thank you!

**Pull request closed without merging**
