### PR TITLE
fluke-dmm: Cleanup Fluke 28x QM handling

### PR DESCRIPTION
**Pull request by andysan**
The code that parses QM responses from Fluke 28x DMMs uses a long series of if-else statements to determine the type of measurement reported by the device. Rewrite this to use a conversion table that contains a mapping between DMM units and Sigrok's internal units.

This change is a first step towards using QDDA to query the DMM and get additional information such as significant digits.

### CODE REVIEW

**Comment by andysan** [comment]
Ping! This is a part of a patch series that lays the foundations to support more features of this Fluke DMM.

**Comment by biot** [comment]
Are you still interested in getting this merged? If not we'll close this -- nice refactor, but I don't have a Fluke 28x to test with anymore. Same for PR #43.

**Comment by andysan** [comment]
> Are you still interested in getting this merged? If not we'll close this -- nice refactor, but I don't have a Fluke 28x to test with anymore. Same for PR #43.

I think it would still be nice to merge this. I'll need to rebase and re-test it though, but I think I should be able to find time for that later this week.

**Comment by andysan** [comment]
I have rebased and retested the changes now. I ended up including some more cleanups since the Fluke driver had a duplicate routine to get the precision of a float. This seemed unnecessary and error prone. I have tested these changes with a Fluke 289 DMM and the count digits change has been tested with a small unit test that I haven't checked in (there wasn't a clean way to link it in the current build system due to the symbol being hidden).

**Review by biot — APPROVED** [review]
Very nice refactor, thanks!

**Comment by abraxa** [comment]
Thank you for your contribution, it was merged as https://sigrok.org/gitaction/libsigrok.git/6669e08..7c9cf3a .

**Pull request closed without merging**
