### PR TITLE
Add new ITECH IT8500 series / BK Precision 8500 series DC Electronic Load driver

### PR DESCRIPTION
**Pull request by tjko**
This driver supports ITECH IT8500 series electronic loads (models IT8511+/IT8511A+/IT8512+/IT8512A+/ IT8512B+/IT8512C+/IT8512H+/IT8513A+/ IT8513B+/IT8513C+/IT8514C+/IT8514B+/ IT8516C+)

Additionally BK Precision 8500 series loads (models 8500, 8502, 8510, 8512, 8514, 8518, 8520, 8522, 8524 & 8526) should work as is, since ITECH appears to be OEM manufacturer of these BK Precision models (programming manual appear to specify identical control protocol to ITECH...).

Driver has been tested with IT8511+ load using sigrok-cli and SmuView.

(replaces: #73)

### CODE REVIEW

**Comment by fgervais** [comment]
Wow I can't believe this, I just received my IT8512A+ 2 days ago and I was casually browsing sigrok to try and get a sense of how much work would be required to add the support. What a coincidence. Thank you very much :)

**Comment by fgervais** [comment]
We're you using the IT-E122 adapter?

**Comment by tjko** [comment]
I've been using isolated USB to TTL-serial adapter from Zeptobit (https://www.zeptobit.com/index.php?category=1) using the pinout shown here: https://www.eevblog.com/forum/testgear/itech-8500-series-(it8511it8512-)-(also-bk8500)-serial-(ttl)-connection/.

**Comment by tjko** [comment]
Found an IT-E132 adapter, it works fine too. So presumably IT-E122 would work fine as well...

**Comment by abraxa** [comment]
Hi, these loads aren't yet documented on the wiki, as you can see here: https://sigrok.org/wiki/Supported_hardware#Digital_loads

It would be great if you could create a page for whichever model is more popular, along with a picture that you yourself took. If you'd like to do this, please join us on IRC for an account: http://webchat.freenode.net/?channels=%23sigrok&uio=MT1mYWxzZQ9a

**Comment by tjko** [comment]
Wiki updated: https://sigrok.org/wiki/ITECH_IT8500_series

**Comment by fgervais** [comment]
I was able to test this branch on a IT8512A+ today but I couldn't make it work.

I seems to work, like I can scan and find the device:

Screenshot from 2020-07-30 21-13-15

but then if I click OK it fails:

```
smuview -D
sr: serial-libsp: Error opening port (16): Device or resource busy.
Configurable::init(): Init  "1"  - key  "Under Voltage Condition Threshold"
Configurable::init(): Init  "1"  - key  "Under Voltage Condition Active"
Configurable::init(): Init  "1"  - key  "Under Voltage Condition Enabled"
Configurable::init(): Init  "1"  - key  "Over Temperature Protection Active"
Configurable::init(): Init  "1"  - key  "Over Temperature Protection Enabled"
Configurable::init(): Init  "1"  - key  "Regulation"
Configurable::init(): Init  "1"  - key  "Over Current Protection Threshold"
Configurable::init(): Init  "1"  - key  "Over Current Protection Active"
Configurable::init(): Init  "1"  - key  "Over Current Protection Enabled"
Configurable::init(): Init  "1"  - key  "Over Voltage Protection Threshold"
Configurable::init(): Init  "1"  - key  "Over Voltage Protection Active"
Configurable::init(): Init  "1"  - key  "Over Voltage Protection Enabled"
Configurable::init(): Init  "1"  - key  "Enabled"
Configurable::init(): Init  "1"  - key  "Current Limit"
Configurable::init(): Init  "1"  - key  "Current"
Configurable::init(): Init  "1"  - key  "Voltage Target"
Configurable::init(): Init  "1"  - key  "Voltage"
Configurable::init(): Init  "ITECH 8512A"  - key  "Samplerate"
Configurable::list_config(): Failed to list config key  "Samplerate" .  not applicable
Init channel  "V1" , channel_start_timestamp =  "2020.07.31 01:12:36.664"
Init channel  "I1" , channel_start_timestamp =  "2020.07.31 01:12:36.664"
Init channel  "P1" , channel_start_timestamp =  "2020.07.31 01:12:36.664"
Init analog base signal  "V1 [V DC]"
Init analog time signal  "V1 [V DC]" , signal_start_timestamp_ =  "2020.07.31 01:12:36.664"
Init analog base signal  "I1 [A DC]"
Init analog time signal  "I1 [A DC]" , signal_start_timestamp_ =  "2020.07.31 01:12:36.664"
Init analog base signal  "P1 [W]"
Init analog time signal  "P1 [W]" , signal_start_timestamp_ =  "2020.07.31 01:12:36.664"
Init channel  "" , channel_start_timestamp =  "2020.07.31 01:12:36.664"
Init analog base signal  "R1 [?]"
Init analog time signal  "R1 [?]" , signal_start_timestamp_ =  "2020.07.31 01:12:36.664"
Init channel  "" , channel_start_timestamp =  "2020.07.31 01:12:36.664"
Init analog base signal  "Wh1 [Wh]"
Init analog time signal  "Wh1 [Wh]" , signal_start_timestamp_ =  "2020.07.31 01:12:36.664"
Init channel  "" , channel_start_timestamp =  "2020.07.31 01:12:36.664"
Init analog base signal  "Ah1 [Ah]"
Init analog time signal  "Ah1 [Ah]" , signal_start_timestamp_ =  "2020.07.31 01:12:36.664"
sr: hwdriver: itech-it8500: Device instance not active, can't start.
sr: session: Could not start itech-it8500 device /dev/ttyUSB2 acquisition.
sr: hwdriver: itech-it8500: Device instance not active, can't stop.
sr: serial-libsp: Attempted serial port write with invalid arguments.
sr: itech-it8500: itech_it8500_send_cmd: error sending command: -3
Caught exception: generic/unspecified error
BaseDevice::close(): Trying to close device  "ITECH 8512A 1.21 0727430103 (/dev/ttyUSB2)"
sr: device: itech-it8500: Device instance not active, can't close.
BaseDevice::close(): Device closed  "ITECH 8512A 1.21 0727430103 (/dev/ttyUSB2)"
```

Any idea why that is?

**Comment by fgervais** [comment]
It's weird it's as if sigrok tries to open the serial port twice.

For the scan it first opens the port and succeeds:

```
openat(AT_FDCWD, "/dev/ttyUSB2", O_RDWR|O_NOCTTY|O_NONBLOCK|O_CLOEXEC) = 18
```

From here I don't see fd=18 being released and then when I click OK it tries to open the same serial port again but fails:

```
openat(AT_FDCWD, "/dev/ttyUSB2", O_RDWR|O_NOCTTY|O_NONBLOCK|O_CLOEXEC) = -1 EBUSY (Device or resource busy)
write(2, "sr: ", 4sr: )                     = 4
write(2, "serial-libsp: Error opening port"..., 64serial-libsp: Error opening port (16): Device or resource busy.
) = 64
```

Of course it's busy you have it open already :)

```
...
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libXcursor", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/x86_64-linux-gnu/libXcursor", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/lib/libXcursor", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/libXcursor", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat(":/qt-project.org/styles/commonstyle/images/dirclosed-16.png", 0x7ffc5d7aed30) = -1 ENOENT (No such file or directory)
stat(":/qt-project.org/styles/commonstyle/images/standardbutton-close-16.png", 0x7ffc5d7ad9a0) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/sys/class/tty/ttyUSB2/device/../busnum", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/sys/class/tty/ttyUSB2/device/../../busnum", O_RDONLY|O_CLOEXEC) = 18
close(18)                               = 0
openat(AT_FDCWD, "/sys/class/tty/ttyUSB2/device/../../devnum", O_RDONLY|O_CLOEXEC) = 18
close(18)                               = 0
openat(AT_FDCWD, "/sys/class/tty/ttyUSB2/device/../../idVendor", O_RDONLY|O_CLOEXEC) = 18
close(18)                               = 0
openat(AT_FDCWD, "/sys/class/tty/ttyUSB2/device/../../idProduct", O_RDONLY|O_CLOEXEC) = 18
close(18)                               = 0
openat(AT_FDCWD, "/sys/class/tty/ttyUSB2/device/../../product", O_RDONLY|O_CLOEXEC) = 18
close(18)                               = 0
openat(AT_FDCWD, "/sys/class/tty/ttyUSB2/device/../../manufacturer", O_RDONLY|O_CLOEXEC) = 18
close(18)                               = 0
openat(AT_FDCWD, "/sys/class/tty/ttyUSB2/device/../../product", O_RDONLY|O_CLOEXEC) = 18
close(18)                               = 0
openat(AT_FDCWD, "/sys/class/tty/ttyUSB2/device/../../serial", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/dev/ttyUSB2", O_RDWR|O_NOCTTY|O_NONBLOCK|O_CLOEXEC) = 18

< Here I just clicked "scan" next I click the OK button, notice no close of fd 18 >

openat(AT_FDCWD, "/sys/class/tty/ttyUSB2/device/../busnum", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/sys/class/tty/ttyUSB2/device/../../busnum", O_RDONLY|O_CLOEXEC) = 19
close(19)                               = 0
openat(AT_FDCWD, "/sys/class/tty/ttyUSB2/device/../../devnum", O_RDONLY|O_CLOEXEC) = 19
close(19)                               = 0
openat(AT_FDCWD, "/sys/class/tty/ttyUSB2/device/../../idVendor", O_RDONLY|O_CLOEXEC) = 19
close(19)                               = 0
openat(AT_FDCWD, "/sys/class/tty/ttyUSB2/device/../../idProduct", O_RDONLY|O_CLOEXEC) = 19
close(19)                               = 0
openat(AT_FDCWD, "/sys/class/tty/ttyUSB2/device/../../product", O_RDONLY|O_CLOEXEC) = 19
close(19)                               = 0
openat(AT_FDCWD, "/sys/class/tty/ttyUSB2/device/../../manufacturer", O_RDONLY|O_CLOEXEC) = 19
close(19)                               = 0
openat(AT_FDCWD, "/sys/class/tty/ttyUSB2/device/../../product", O_RDONLY|O_CLOEXEC) = 19
close(19)                               = 0
openat(AT_FDCWD, "/sys/class/tty/ttyUSB2/device/../../serial", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/dev/ttyUSB2", O_RDWR|O_NOCTTY|O_NONBLOCK|O_CLOEXEC) = -1 EBUSY (Device or resource busy)
write(2, "serial-libsp: Error opening port"..., 64serial-libsp: Error opening port (16): Device or resource busy.
openat(AT_FDCWD, "/usr/share/mime/packages", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = 19
close(19)                               = 0
stat(":/icons/document-open-folder.png", 0x7ffc5d7adf10) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/x86_64-linux-gnu/qt5/plugins/iconengines/libqsvgicon.so", O_RDONLY|O_CLOEXEC) = 19
close(19)                               = 0
write(2, "BaseDevice::close(): Trying to c"..., 90BaseDevice::close(): Trying to close device  "ITECH 8512A 1.21 0727430103 (/dev/ttyUSB2)"
write(2, "device: itech-it8500: Device ins"..., 63device: itech-it8500: Device instance not active, can't close.
write(2, "BaseDevice::close(): Device clos"..., 81BaseDevice::close(): Device closed  "ITECH 8512A 1.21 0727430103 (/dev/ttyUSB2)"
openat(AT_FDCWD, "/sys/devices/system/cpu/online", O_RDONLY|O_CLOEXEC) = 19
close(19)                               = 0
close(3)
```

I'm not sure what is going on here.

**Comment by tjko** [comment]
I haven't tried it with smuview for couple months... My unit is running some battery tests now, and logging data, so I can't test msuview for day or two unfortunately....

 Are you using latest smuview from git repo or some older version?

Btw, have you tried with sigrok-cli, does it work fine with it?

# sirgok-cli -d itech-it8500:conn=/dev/ttyUSB2 --samples 3

Does above work? If not can you try with verbose logging (add "-l 5" to command line options).

**Comment by fgervais** [comment]
No problem, I'll give it a bit more time today and see if I can find the problem.

I'm using smuview from the git repo, I'm currently running top of master:

```
smuview -V
SmuView 0.0.4-git-4b5f367
```

I don't know I haven't built sigrok-cli, I'll give it a try if I can't find the issue.

**Comment by fgervais** [comment]
Just quick update before I leave for the day, 

Based on the atten-pps3xxx, I added the following which at first glance seems to fix the problem I had:

```patch
diff --git a/src/hardware/itech-it8500/api.c b/src/hardware/itech-it8500/api.c
index 94c412ed..add4d32f 100644
--- a/src/hardware/itech-it8500/api.c
+++ b/src/hardware/itech-it8500/api.c
@@ -291,6 +291,7 @@ static GSList *scan(struct sr_dev_driver *di, GSList *options)
 
 
        g_free(response);
+       serial_close(serial);
 
        return std_scan_complete(di, g_slist_append(NULL, sdi));
 ```

**Comment by tjko** [comment]
@fgervais, thanks for finding out the problem and solution as well.  Odd that I didn't have any issue launching smuview though...

I checked in fix: 06fabab82f6932793c1bc6af230f00f27f26c1e5

It should now work ok both in smuview and sigrok-clie?


Btw, as you seem to have different model, curious if   "--scan -l 3" produces accurate specs for your unit as well?

```
# sigrok-cli -d itech-it8500:conn=/dev/ttyUSB0 --scan -l 3
sr: itech-it8500: Probing serial port: /dev/ttyUSB0
sr: itech-it8500: Model name: 8511 (v1.13)
sr: itech-it8500: Address: 0
sr: itech-it8500: Serial number: 07172xxxxx
sr: itech-it8500: Barcode:  6000190107172xxxxx
sr: itech-it8500: Max current: 30 A
sr: itech-it8500: Max power: 200 W
sr: itech-it8500: Voltage range: 0.1 - 120.0 V
sr: itech-it8500: Resistance range: 0.05 - 7500.00 Ohm
sr: itech-it8500: Mode: CC
sr: itech-it8500: State: OFF
sr: itech-it8500: Default sample rate: 10 Hz
sr: itech-it8500: Maximum sample rate: 60 Hz
The following devices were found:
itech-it8500 - ITECH 8511 1.13 [S/N: 07172xxxxx] with 3 channels: V1 I1 P1
```

**Comment by fgervais** [comment]
Thanks, your fix seems to work for me.

```
$ LD_LIBRARY_PATH=${INSTALL_DIR}/lib ${INSTALL_DIR}/bin/sigrok-cli -d itech-it8500:conn=/dev/ttyUSB2 --scan -l 3
sr: itech-it8500: Probing serial port: /dev/ttyUSB2
sr: itech-it8500: Model name: 8512A (v1.21)
sr: itech-it8500: Address: 0
sr: itech-it8500: Serial number: 07274xxxxx
sr: itech-it8500: Barcode:  6021430107274xxxxx
sr: itech-it8500: Max current: 30 A
sr: itech-it8500: Max power: 320 W
sr: itech-it8500: Voltage range: 0.1 - 150.0 V
sr: itech-it8500: Resistance range: 0.05 - 7500.00 Ohm
sr: itech-it8500: Mode: CC
sr: itech-it8500: State: OFF
sr: itech-it8500: Default sample rate: 10 Hz
sr: itech-it8500: Maximum sample rate: 15 Hz
The following devices were found:
itech-it8500 - ITECH 8512A 1.21 [S/N: 07274xxxxx] with 3 channels: V1 I1 P1
```

**Comment by tjko** [comment]
Replaced by #92

**Pull request closed without merging**
