### PR TITLE
PICO code release

### PR DESCRIPTION
**Pull request by pico-coder**
I thought I deleted the "[raspberrypi-pico: Initial driver skeleton.](https://github.com/sigrokproject/libsigrok/pull/179" but it's still around, but let's see how this pull request comes out...

### CODE REVIEW

**Comment by pico-coder** [comment]
ok. I think this all looks good, the real driver files and the Makefiles etc are both in.  I did delete pull 179, but the commits that were first created for it "[raspberrypi-pico: Initial driver skeleton.]" are still there.
Tabs removed, copyrights updated, removed a few excessive parens.

**Comment by pico-coder** [comment]
Oh, and I did run the "make check" regression and it passed, and reloaded everything through pulseview and it looks good.

**Comment by jr-oss** [comment]
Try to think as a reviewer, who is willing to spend time: What would motivate you to review foreign code and what would make your work easier?
- a guide how to use the pico as LA and/or scope
- the necessary pico firmware (u2f-format?). Don't expect anybody to look for it.
- documentation of the protocol, data flow, ...?
- make the code readable. This is imho not readable "if(!(devc->buffer)){sr_err("ERROR:serial buffer malloc fail");return SR_ERR_MALLOC;}"

Again:
*Read* the file HACKING http://sigrok.org/gitweb/?p=libsigrok.git;a=blob;f=HACKING;hb=HEAD
with coding style reference (follow the link and *read* it) https://www.kernel.org/doc/html/latest/process/coding-style.html
Hint: Indentation is by tab, not spaces
(There is even an emacs settings for formatting)

Maybe you can also look at: https://en.cppreference.com/w/c/language/operator_precedence
"(devc->buffer)" does not need braces, but confuses readers.

Last but not least: inform the maintainers/supporting users via irc or mailing list that there is a PR (and where to find it)
(but you probably know by know, after reading HACKING ;-)

**Comment by pico-coder** [comment]
Every time I've reviewed code patches I've just disabled whitespace diffs so tabs and spaces have never been a problem, but I'll convert the spaces to tabs.

I did post to both IRC and to mailing list asking for pull review (though really it was just a pointer to some files I was asking someone to copy in).  I never got a response from any approvers, so I filed the pull requests here.  The email I sent to the reflector was titled "Pull request for libsigrok driver for Raspberry PI PICO rp2040 board".

My github repo (https://github.com/pico-coder/sigrok-pico) has a few documents on getting started and how to program the hardware.    It also has precompiled uf2 files the user can directly program the hardware with.

While the RP2040/PICO board definitely has a firmware, it can't be easily loaded across the USB CDC/Serial interface so it's up to the user to program the board themselves using existing uf2 loading flows before starting to use sigrok.   So I think it is best left outside of sigrok.

I don't understand why this isn't readable:
if(!(devc->buffer)){sr_err("ERROR:serial buffer malloc fail");return SR_ERR_MALLOC;}"
If malloc returns a null pointer it means it failed to allocate memory so I print a corresponding error indication and return.

**Comment by pico-coder** [comment]
So I tied the emacs code from https://www.kernel.org/doc/html/latest/process/coding-style.html but that still left combinations of codes and spaces.
I also installed indent and ran indent -kr -i8 per the link above and that also left spaces in some cases.
I can't seem to find any magic incantation of emacs that allows me to always enter tabs instead of spaces and I've tried gnu emacs and xemacs.
I'm really out of ideas on how to get what you consider to be a good editor, but if you have suggestions I'm open.
I'm running a raspberry pi model 3 because I can't buy a 4, and the real editors/IDEs run too slow on it.
Going to close this and try another attempt with the "indent" versions of the code.

**Comment by jr-oss** [comment]
> Every time I've reviewed code patches I've just disabled whitespace diffs so tabs and spaces have never been a problem, but I'll convert the spaces to tabs.

I am neither maintainer nor particularly involved in the project and just want to point out possible obstacles for integration.
You want your code to get integrated into (and maintained by) sigrok, so I think it is fair to follow the coding guidelines of the project and make the review process as smooth as possible.

> 
> I did post to both IRC and to mailing list asking for pull review (though really it was just a pointer to some files I was asking someone to copy in). I never got a response from any approvers, so I filed the pull requests here. The email I sent to the reflector was titled "Pull request for libsigrok driver for Raspberry PI PICO rp2040 board".

Maintainers have regular jobs and families and are taking care of the project in their spare time and there are many PRs pending.
I looked up your mail and there are already good points, why the pico is an interesting device. Put this information into the PR, also.

The link you posted in IRC is outdated now, because with every change you cancel the PR and start a new one loosing any feedback provided, so far.
You can update your branch and everybody can see the progress.
Once the code is acceptable, you can squash commits and clean up for integration.

> 
> My github repo (https://github.com/pico-coder/sigrok-pico) has a few documents on getting started and how to program the hardware. It also has precompiled uf2 files the user can directly program the hardware with.

Point to it in your PR  and give hints how to use the device.

> 
> While the RP2040/PICO board definitely has a firmware, it can't be easily loaded across the USB CDC/Serial interface so it's up to the user to program the board themselves using existing uf2 loading flows before starting to use sigrok. So I think it is best left outside of sigrok.

Mention this in the PR, point to some (existing) instructions and provide a uf2 file in your repo or somewhere else.
Imagine a reviewer has access to a pico and is willing to test your code, but can't because there is no easy way to get the firmware.

> 
> I don't understand why this isn't readable: if(!(devc->buffer)){sr_err("ERROR:serial buffer malloc fail");return SR_ERR_MALLOC;}" If malloc returns a null pointer it means it failed to allocate memory so I print a corresponding error indication and return.

Maybe because I am getting older and have problems to identify the particular parts (statement, parameters, conditions) of that line. Icouldhavewrittenmyanswer(withoutblanks)and(random)braces to emphasize my point.

**Comment by pico-coder** [comment]
I thought when I was working with you that you were a maintainer because you were marked as someone who had contributed.  I was doing this all in the context of someone who was aware of all the changes and thus wasn't copying all the information over.

I updated 181 with more information and updated the pull request on the email list.

I'm still not sure how to update a pull request of a fork.  All the fork stuff is based on github clicks and I can't seem to find a button that says repull from the latest version of the fork without just cancelling the request and starting over.  But for now I'll wait till a maintainer gets back to me and figure out where to go from there.

Thanks for your feedback.

**Comment by CRImier** [comment]
Seems like Pulseview/sigrok people aren't all that active at the moment. I also checked my mailing list and, indeed, both messages are there, they didn't go to spam or anything. There's [more than enough background linked there](https://github.com/pico-coder/sigrok-pico), available from the first email, and maintainers can check that anytime, it doesn't take more than a minute, and it's fair to expect a minute of time from a maintainer when they're reviewing a PR.

I'm pretty sure the problem with this PR isn't formatting or lack of background (the documentation in the repo itself is extensive!!), it's that nobody seems to have looked at it yet. It's especially not fair to ask for a guide, given that [it's been there for ages](https://github.com/pico-coder/sigrok-pico/blob/main/GettingStarted.md), linked in the first mailing list message. "Don't expect anybody to look for it." isn't fair, either, given that the firmware always was a few steps away.

1. "Imagine a reviewer has access to a pico and is willing to test your code"
2. "but can't because there is no easy way to get the firmware."

The first part of this doesn't seem to be true at the moment, and the last part was never true as far as a single-minute search indicates. I recommend we wait for the former, like [everybody else seems to be doing](https://github.com/sigrokproject/libsigrok/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc) with their pull requests going without feedback for quite a bit of time. I recommend putting a bit more effort before providing feedback, lest the feedback ends up being confusing; providing good and valuable feedback requires that you spend effort on it.

I have some experience compiling the whole sigrok stack on Linux, previously shared it on sigrok-devel ML. I'll see if, while sigrok maintainers aren't here to chime in, I could add my instructions to the sigrok-pico repo, so that people can start hacking!

@pico-coder thank you so much for your work, and hopefully we can see it addressed soon!

**Comment by jr-oss** [comment]
If I insulted anybody, please accept my apologies.
My intention was to give feedback, instead of letting the author hang on for a long time without getting any response.
Communication is not my favorite subject ;-)

Please don't blame the maintainers of the project, because of my feedback.
I am not a maintainer, but have been following the project for some time and saw feedback from maintainers or people with access to the mainline repo.
Based on that I assumed, that my feedback with links to specific information and examples is helpful to get the code accepted.
(look for "style" in the commit messages to get examples about whitespaces)

But you just picked out my complaint, that the PR does not point to the required firmware. 
Your assumption is, that everybody is subscribed to the mailing list and gathers all information, blaming those that don't follow the list for not knowing.
<sarcasm>This really motivates me to give further feedback</sarcasm>

I started to look into the PR in the first place, because it looked interesting, but now I am not that motivated any longer.

**Comment by CRImier** [comment]
Hey! Sorry for a message that was coming from an irritated place. Likely because of me being irritated on others' behalf when PRs and mailing list messages go unanswered substantially or at least given a timeline or quick look-over. Given your intentions that are now more clear to me, it was inappropriate to have my irritation directed at you here.

I hope this helps, and I'm sorry for passing my irritation further. Thank you for your help so far.
Let's all hope these PRs can get some well-deserved attention!

**Comment by jr-oss** [comment]
No problem and thanks for your explanation.

**Pull request closed without merging**
