### PR TITLE
Add Rigol DS1xxxZ Plus & RPL1116 digital ports support

### PR DESCRIPTION
**Pull request by AristarchosOfSamos**
The DS1xxxZ Plus models are MSO ready, they contain the connector to attach a RPL1116 16 port digital head.
Having a DS1xxxZ Plus and a connected RPL1116 effectively the instrument becomes a MSO1xxxZ.

PulseView determines the instrument's abilities by examining the instrument's reported ID string, so for the DS1104Z Plus it gives attributes from here
https://github.com/sigrokproject/libsigrok/blob/0db1b189bee3ffe5c6ea39d7ca2e62715856b538/src/hardware/rigol-ds/api.c#L277

But that "CH_INFO(4, false)" means 4 analog channels and NO digital channels.
As said though, the DS1xxxZ Plus variants got the D0..D15 digital ports abilities already so this line treats the DS1xxxZ Plus as a plain DS1xxxZ without the digital ports.

A very simple remedy is to change the CH_INFO(4, false) to CH_INFO(4, true)
So those two lines should be
from
{SERIES(DS1000Z), "DS1074Z Plus", {5, 1000000000}, CH_INFO(4, false), std_cmd},
{SERIES(DS1000Z), "DS1104Z Plus", {5, 1000000000}, CH_INFO(4, false), std_cmd},
to
{SERIES(DS1000Z), "DS1074Z Plus", {5, 1000000000}, CH_INFO(4, true), std_cmd},
{SERIES(DS1000Z), "DS1104Z Plus", {5, 1000000000}, CH_INFO(4, true), std_cmd},
and the problem will be solved.

This is the proposed solution of the sigrok bugzilla report
https://sigrok.org/bugzilla/show_bug.cgi?id=1831

### CODE REVIEW

**Comment by fenugrec** [comment]
Changeset looks simple enough and the explanation in your bugzilla comments are interesting.

However the commit message is... underwhelming. Look at previous commits for examples of formatting. 
And I recommend adding to it a concise summary of your findings from the bugzilla as to the what and why of this change.

**Review by fenugrec — CHANGES_REQUESTED** [review]
as mentioned, changeset looks OK but commit message very insufficient

**Comment by AristarchosOfSamos** [comment]
@fenugrec 
Commit message changed as requested.

**Comment by Duality4Y** [comment]
I am looking at this branch with such a stare and fixation and anticipation you wouldn't believe 👀

**Comment by abraxa** [comment]
Merged as https://sigrok.org/gitaction?p=libsigrok.git;a=commit;h=48385ca229bee3e267108b7cc8ab3c99edaf77a4 with some additional commit comments. Thank you!

**Pull request closed without merging**
